# Generated by Django 5.0.7 on 2024-07-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_semester_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='effects',
            field=models.ManyToManyField(null=True, to='panel.courseeffect'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(null=True, to='panel.coursetag'),
        ),
    ]
