# Generated by Django 5.0.7 on 2024-07-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_course_effects_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='effects',
            field=models.ManyToManyField(blank=True, to='panel.courseeffect'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, to='panel.coursetag'),
        ),
    ]
