# Generated by Django 5.0.7 on 2024-07-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_course_effects_alter_course_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
