# Generated by Django 5.0.7 on 2024-07-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_semester_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetype',
            name='shortcut',
            field=models.CharField(default='', max_length=10),
        ),
    ]
