# Generated by Django 5.0.7 on 2024-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_coursetype_shortcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetag',
            name='shortcut',
            field=models.CharField(default='', max_length=100),
        ),
    ]
