# Generated by Django 5.0.7 on 2024-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_coursetag_shortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='shortcut',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
