# Generated by Django 5.0.7 on 2024-07-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_userplan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='type',
            field=models.CharField(choices=[('engineer', 'Eng'), ('bachelors', 'Bac')], default='', max_length=20),
        ),
    ]
