# Generated by Django 5.0.7 on 2024-08-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_userplan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='type',
            field=models.CharField(choices=[('Engineer', 'Eng'), ('Bachelor', 'Bac')], default='', max_length=20),
        ),
    ]
